name: pydata-issst
channels:
    - defaults
    - conda-forge
    - damianavila82
dependencies:
    - python=3.6
    - conda
    - matplotlib
    - numpy
    - pandas
    - jupyter
    - jupyterlab
    - seaborn
    - nb_conda_kernels
    - xlrd
    - joblib
    - scikit-learn
    - openpyxl
    - altair
    - vega3
    - rise
    - jupyter_contrib_nbextensions
    - pip:
        - vega_datasets
